### ISSUE TITLE
`selfLink` is not getting populated

### ISSUE THREAD

**Issue by nstogner** [GoogleCloudPlatform/terraform-google-conversion#10]
`selfLink` is referred to in the CAI `Name` field.

example:
```go
	if obj, err := GetComputeDiskApiObject(d, config); err == nil {
		return Asset{
			Name: fmt.Sprintf("//compute.googleapis.com/%s", obj["selfLink"]),
```

However, it does not look like it ever gets set.

**Comment by chrisst** [comment]
fyi - all access to `self_link` should be wrapped in a method which can parse both a relative `self_link` or a fully qualified one.

**Comment by melinath** [comment]
This repository is not intended to have issues filed against it. Please open an issue (if still needed) at https://github.com/GoogleCloudPlatform/terraform-validator
