### ISSUE TITLE
Expose mapping of resource type to conversion function

### ISSUE THREAD

**Issue by nstogner** [GoogleCloudPlatform/terraform-google-conversion#3]
It would be really useful to expose a generated map of terraform resource type to the associated converter function, i.e:

```go
map[string]ConverterFunc{
	"google_compute_disk": GetComputeDiskApiObject,
	...
}
```

**Comment by melinath** [comment]
This repository is not intended to have issues filed against it. Please open an issue (if still needed) at https://github.com/GoogleCloudPlatform/terraform-validator
